### PR TITLE
Add cycle breaker transform

### PR DESCRIPTION
**Pull request by emilhe**
Add `CycleBreaker` component and associated `CycleBreakerTransform`. The following code,

```
import dash_mantine_components as dmc
from dash.exceptions import PreventUpdate
from enrich import DashProxy, html, Output, Input

app = DashProxy()
app.layout = html.Div([
    dmc.NumberInput(id="celsius", label="Celsius"),
    dmc.NumberInput(id="fahrenheit", label="Fahrenheit"),
])


@app.callback(Output("celsius", "value"), Input("fahrenheit", "value"))
def update_celsius(value):
    if value is None:
        raise PreventUpdate()
    return (float(value) - 32) / 9 * 5


@app.callback(Output("fahrenheit", "value"), Input("celsius", "value"))
def update_fahrenheit(value):
    if value is None:
        raise PreventUpdate()
    return float(value) / 5 * 9 + 32


if __name__ == '__main__':
    app.run_server()

```

raises a error like,

`"Error: Dependency Cycle Found: celsius.value -> fahrenheit.value -> celsius.value"`

The new transform makes it possible to remove the error simply by mounting the transform with a specification on where to break the cycle,

```
import dash_mantine_components as dmc
from dash.exceptions import PreventUpdate
from enrich import DashProxy, html, Output, Input, CycleBreakerTransform

cycle_breaks = [("fahrenheit", "value")]
app = DashProxy(transforms=[CycleBreakerTransform(cycle_breaks=cycle_breaks)])
app.layout = html.Div([
    dmc.NumberInput(id="celsius", label="Celsius"),
    dmc.NumberInput(id="fahrenheit", label="Fahrenheit"),
])


@app.callback(Output("celsius", "value"), Input("fahrenheit", "value"))
def update_celsius(value):
    if value is None:
        raise PreventUpdate()
    return (float(value) - 32) / 9 * 5


@app.callback(Output("fahrenheit", "value"), Input("celsius", "value"))
def update_fahrenheit(value):
    if value is None:
        raise PreventUpdate()
    return float(value) / 5 * 9 + 32


if __name__ == '__main__':
    app.run_server()
```

### CODE REVIEW

**Comment by emilhe** [comment]
It guess a nice feature of this transform would be to add an (optional) delay on the update cycle, i.e. not allow updates in the cycle to be faster than some frequency. Currently, if the example is modified with a bug in the conversion of C to F (or F to C), an infinite amount of callback invocations are dispatches as fast as the client/server can execute them.

**Comment by TomaszRewak** [comment]
It seems that the PR is missing the `CycleBreaker.py`.

**Comment by TomaszRewak** [comment]
With the current implementation of the `CycleBreakerTransform` it will not be possible to break cycles when using the `Dash` object directly from the `enrich.py`. One would have to always create a `DashProxy` manually, providing all the required transform objects.

Wouldn't it be better (and more inline with how other transform objects work), to make it a configuration of a callback level?

Something like:
```py
...

app = DashProxy(transforms=[CycleBreakerTransform()])

...

@app.callback(Output("celsius", "value"), Input("fahrenheit", "value"), break_cycles=[("fahrenheit", "value")])
def update_celsius(value):
    ...

...
```

Or potentially even like this (where all inputs of the function would be broken automatically):
```py
@app.callback(Output("celsius", "value"), Input("fahrenheit", "value"), break_cycles=True)
def update_celsius(value):
    ...
```

This also means that if there is another callback that depends on `("fahrenheit", "value")` but does not form a cycle with it, it will not be unnecessarily altered. Like in this example:

```py
...

app.layout = html.Div([
    dmc.NumberInput(id="celsius", label="Celsius"),
    dmc.NumberInput(id="fahrenheit", label="Fahrenheit"),
    html.Div(id="output")
])


@app.callback(Output("celsius", "value"), Input("fahrenheit", "value"))
def update_celsius(value):
    ...


@app.callback(Output("fahrenheit", "value"), Input("celsius", "value"))
def update_fahrenheit(value):
    ...

@app.callback(Output("output", "children"), Input("celsius", "value"), Input("fahrenheit", "value"))
def update_celsius(celsius, fahrenheit):
    return f"It is {celsius} celsius and {fahrenheit} fahrenheit"

...
```

**Comment by emilhe** [comment]
An implementation at the callback level was actually also my initial though. However, I wasn't sure how the syntax should look like.

1) My first idea was to add a callback level keyword argument (similar to you suggestion). However, while it seems like a fine option for simple callbacks as in the example, it was less obvious for me what to do with callback with _many_ inputs/outputs. Adding breakers for **all** of them seems excessive

2) My next idea was to add dependency level keyword argument, i.e. something like,

```
@app.callback(Output("celsius", "value", break_cycle=True), Input("fahrenheit", "value"))
def update_celsius(value):
    ...
```

which makes it possible to specify what cycles to break (and which ones not to). What I don't like about this syntax is that it's not really clear if the break `break_cycle` keyword belongs to the output of this callback, or this input of the other callback, i.e.

```
@app.callback(Output("fahrenheit", "value"), Input("celsius", "value", break_cycle=True))
def update_fahrenheit(value):
    ...
```

or any other callbacks involving the property ("celsius", "value"). I think your initial syntax suffers from the same kind of issue. Ideally, I would like a syntax where there is only one place (preferable an obvious only) to specify the break. Please let me know, if you have more ideas :)

With regard to ingrain with the Dash object, one option would be to add a keyword argument, i.e. the syntax would then be something like,

```
app = Dash(cycle_breaks=[("fahrenheit", "value")])
```

Another option would be to add breaks automatically where cycles are detected. But I think this option wouldn't yield the necessary control to the user (there could be many places to break a cycle, and performance might be impacted based on the where the break is performed, i.e. the user should be able to control it).

**Comment by emilhe** [comment]
@TomaszRewak I just checked in `CycleBreaker.react.js` if that's what you mean? The `.py` files are never checked in

**Comment by TomaszRewak** [comment]
Ah, yes, I was indeed thinking about the `CycleBreaker.react.js`

I see your point and I agree - it's better to have a clear single place where this thing needs to be configured. It must be obvious to the user.

Just for completeness, there is one other alternative, but I don't know how do I feel about it myself. You could add a `CycleBreakInput` class (similarly to how there is a `Trigger` class for the `TriggerTransform`). The thing I like least about this approach is that I cant think of any good name for that thing.

> Adding breakers for all of them seems excessive

That's true. Probably the overall cleanest solution would be to have a callback-level `break_cycles` boolean flag and to generate the breakers only for the inputs that indeed belong to a cycle. But for that we would have to implement a cycle detection logic ourselves.

The thing I'm probably most afraid when it comes to the global configuration (`Dash(cycle_breaks=[...])`) is that example of `update_output` I gave, where the breaking happens also for a callback that does not participate in the cycle. That's a change in behavior that users might not expect. Dash has internally this feature where if you chain callbacks, it will only apply the result of the final callback calculation once all callbacks on which it depends finish execution (also including dependencies of the dependencies of that callback). It's well described in "Dash App With Chained Callbacks" section of the https://dash.plotly.com/basic-callbacks

Following the docs, for this code:

``` py
from dash import Dash, dcc, html, Input, Output

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = Dash(__name__, external_stylesheets=external_stylesheets)

all_options = {
    'America': ['New York City', 'San Francisco', 'Cincinnati'],
    'Canada': [u'Montréal', 'Toronto', 'Ottawa']
}
app.layout = html.Div([
    dcc.RadioItems(
        list(all_options.keys()),
        'America',
        id='countries-radio',
    ),

    html.Hr(),

    dcc.RadioItems(id='cities-radio'),

    html.Hr(),

    html.Div(id='display-selected-values')
])


@app.callback(
    Output('cities-radio', 'options'),
    Input('countries-radio', 'value'))
def set_cities_options(selected_country):
    return [{'label': i, 'value': i} for i in all_options[selected_country]]


@app.callback(
    Output('cities-radio', 'value'),
    Input('cities-radio', 'options'))
def set_cities_value(available_options):
    return available_options[0]['value']


@app.callback(
    Output('display-selected-values', 'children'),
    Input('countries-radio', 'value'),
    Input('cities-radio', 'value'))
def set_display_children(selected_country, selected_city):
    return u'{} is a city in {}'.format(
        selected_city, selected_country,
    )


if __name__ == '__main__':
    app.run_server(debug=True)
```

> If you change the value of the countries dcc.RadioItems component, Dash will wait until the value of the cities component is updated before calling the final callback. This prevents your callbacks from being called with inconsistent state like with "America" and "Montréal".

Now let's say that we add another `RadioItems` to out layout with phone extension numbers (+48, +1 etc.). As the extension is dependent on the country, we will add a cyclical callback to update one selection based on the other and vice versa. To break it we would specify that `Dash(cycle_breaks=[("countries-radio", "value")])`. The problem is that it would not only (as expected) break the cycle between the countries `RadioItems` and phone extensions `RadioItems`, but it will also introduce the breaker in those other callbacks that depend on the `("countries-radio", "value")` - potentially leading to a situation where the app would display `"America" and "Montréal"` - which Dash by default protect against.

**Comment by emilhe** [comment]
Ah, I didn't really think about it that way. I was thinking that the intention from the start was to break "all chains involving a specific prop". I guess in principle you are right, that we only want to break _specific_ links in the callback chain(s), though I am not sure how often it will make a difference in practice.

If this is indeed the case, the specification `("fahrenheit", "value")` is not sufficient - the information on _what_ links to break is missing. I guess the only sane way to collect this information would be the dependency-level keyword argument. 

I am trying to wrap my head around how an implementation of that concept would look. So, for starters, does it make the most sense to specify the cycle break on `Input` or `Output`? Or do we need both?

**Comment by emilhe** [comment]
With the dependency level keyword syntax, my working example now looks like this,

```
import dash_mantine_components as dmc
from dash.exceptions import PreventUpdate
from enrich import Dash, html, Output, Input

app = Dash()
app.layout = html.Div([
    dmc.NumberInput(id="celsius", label="Celsius"),
    dmc.NumberInput(id="fahrenheit", label="Fahrenheit"),
])


@app.callback(Output("celsius", "value"), Input("fahrenheit", "value", break_cycle=True))
def update_celsius(value):
    if value is None:
        raise PreventUpdate()
    return (float(value) - 32) / 9 * 5


@app.callback(Output("fahrenheit", "value"), Input("celsius", "value"))
def update_fahrenheit(value):
    if value is None:
        raise PreventUpdate()
    return float(value) / 5 * 9 + 32


if __name__ == '__main__':
    app.run_server()
```

I think I agree that this is actually better than before :). @TomaszRewak Du you like the keyword name, i.e. `break_cycle`? Or do you have a better idea? Or would you prefer a `CycleBreakerInput` component? A such component would make the code more verbose (which I guess is good), but it would require another import (which I think is bad).

**Comment by TomaszRewak** [comment]
I think the syntax you suggested (`Input("fahrenheit", "value", break_cycle=True)`) works fine!

**Pull request merged**
