### PR TITLE
add a ComposedComponentMixin

### PR DESCRIPTION
**Pull request by sdementen**
hello @emilhe ,

I have implemented the feature discussed in #21 
Could you have a first look at it and give me your feedback ? 
tx!

### CODE REVIEW

**Comment by emilhe** [comment]
I have only had time to scout briefly through the code, but your approach looks really cool! I'll get back with some more comments, when i get time to look properly at the code :)

**Comment by sdementen** [comment]
just read the message from @oegedijk on its new project https://github.com/oegedijk/dash_oop_components

**Comment by sdementen** [comment]
as I rely on `ComposedComponentTransform.apply(...)` to post-process components and callbacks, if I add a composed component after the initial layout (e.g. if I click a button, I add to a children div a ComposedComponent), the feature does not work properly. 

I am thinking about hijacking the `ComposedComponentMixin.__init__` to handle part of its logic (currently in the `ComposedComponentTransform.apply` function) when the component is created. The `__init__` could get back a reference to the Dash app (needed to add callbacks), if called during a Flask request (ie dynamic addition of a component) tx to 
```
    def __init__(self, id, **kwargs):
        from flask import current_app
        try:
            app = current_app.dash_app
        except RuntimeError:
            app = None # not running in the context of a Flask request
        ...
```
The `dash_app` attribute does not exist yet but could be initialised at the end of the `Dash.__init__` method with a
```
# region Transformer implementations

class Dash(DashTransformer):
    def __init__(self, *args, output_defaults=None, **kwargs):
        output_defaults = dict(backend=None, session_check=True) if output_defaults is None else output_defaults

        transforms = [TriggerTransform(), ComposedComponentTransform(app=self), NoOutputTransform(), GroupTransform(),
                      ServersideOutputTransform(**output_defaults)]
        super().__init__(*args, transforms=transforms, **kwargs)
        self.server.dash_app = self

# endregion
```

Hence, the logic to apply to a ComposedComponentMixin could be more robust.

There is still the second part of the logic today in my `ComposedComponentTransform.apply` function that handles the rewriting of the "own" properties and the aliases of the ComposedComponents for the standard dash callbacks that refers to the component. 
Applying this at each and every creation of a ComposedComponentMixin could be expensive in terms of performance. 
Maybe worth the run it once at the beginning with all pre-existing components (when the `current_app` has not yet a context and `app = None` in the `ComposedComponentMixin.__init__`) and the run it incrementally for each newly added component. There could be even a need to "unregister" a ComposedComponentMixin if it is not used anymore.
(the second part of the logic)
```
        # rewrite all arguments of callbacks that refers to properties of ComposedComponent

        # get component that need translation to data store
        id2comp = {(comp.id["component_parent_id"], comp.id["subcomponent_id"]): comp for comp in
                   components_with_ids if isinstance(comp.id, dict) and "subcomponent_id" in comp.id}
        # get aliases
        alias = {(comp.id, prop): (dict(component_type=comp._composed_type,
                                        component_parent_id=comp.id,
                                        subcomponent_id=subid), subprop) for comp in components_with_ids for
                 prop, (subid, subprop) in getattr(comp, "_aliases", {}).items()}

        # convert properties linked to data stores
        for callback in callbacks:
            for prop in callback["sorted_args"]:
                if isinstance(prop.component_id, dict):
                    # composed property, do not transform
                    # TODO: handle cases where the ComposedComponent property is a dict
                    continue

                # transform composed component own properties
                proxy_prop_via_store = id2comp.get((prop.component_id, prop.component_property))
                if proxy_prop_via_store is not None:
                    prop.component_id = proxy_prop_via_store.id
                    prop.component_property = "data"
                else:
                    # transform aliases
                    proxy_prop_via_alias = alias.get((prop.component_id, prop.component_property))
                    if proxy_prop_via_alias is not None:
                        prop.component_id, prop.component_property = proxy_prop_via_alias

```

**Comment by sdementen** [comment]
I have tried the approach described above yet it does not work when adding dynamically a ComposedComponentMixin to an existing layout.
I fear it is due to the `_setup_server` (or other methods) having to run before the dash_extensions working.
Do the other extensions (Trigger, ServersideOutput, ...) work when added dynamically (like creating new callbacks in a callback) ?
```
@app.callback(Input("btn", "n_clicks"), Output("inject", "children"))
def update_out(n_clicks):
    print(n_clicks)
    if n_clicks:
        @app.callback(...)
        def dynamic_callback():
             ...
        return [ EnhanceSlider(id="third", size=8) ]
    raise PreventUpdate()
```

**Comment by emilhe** [comment]
No, unfortunately not. AFAIK, it is currently a limitation of Dash that all callbacks must be defined prior to running the app :/

**Comment by sdementen** [comment]
OK, that eases a bit the problem.

First issue: if a ComposedComponent is only added dynamically (after initializing the app), its callbacks will have never been registered ==> we should have a kind of `app.register_composed_component(component class)` (or some global variable with some metaclass) to allow to call `ComposedComponentMixin.declare_callbacks` prior to running the app.

Second issue: rewriting callbacks with Pattern Matching. Today, I am assuming the id of the composed components are string and I transform them in dict to mangle them. I should check that if the id of the composed component is a dict, that everything works correctly

**Comment by emilhe** [comment]
I am not sure i understand your comments on the "first issue". Since callbacks cannot be registered on the app after the server has been started, i don't see why an `app.register_composed_component(component class)` statement would help. Could you elaborate? 

The only immediate solution i see would be to register per-class wild card callbacks. Have you considered that option? It's a bit tedious, and i am not sure about performance implications, but i guess it could work.

**Comment by sdementen** [comment]
"The only immediate solution i see would be to register per-class wild card callbacks. " ==> this is indeed what I do here https://github.com/thedirtyfew/dash-extensions/pull/26/files#diff-14bed3f152411b49d0c42cb36f55e16d748eca696a3d3727e1b093cf4a39ed1aR260 
However, this assumes that Dash finds at least one instance of the ComposedComponent class when iterating on `self._app.layout._traverse_ids()` (https://github.com/thedirtyfew/dash-extensions/pull/26/files#diff-14bed3f152411b49d0c42cb36f55e16d748eca696a3d3727e1b093cf4a39ed1aR254).
If this would not be the case (because the ComposedComponent instance is only added afterwards, dynamically), we should nevertheless force the callback registration for this class before the server starting ==> we need to tell `ComposedComponentTransform.apply` to also handle the callbacks of these "registered ComposedComponent".
Is it clearer ?

**Comment by emilhe** [comment]
Ah, yes. Sorry, i didn't yet have time to look closely at the code. Then it makes sense ;)

**Comment by sdementen** [comment]
I have fixed the two issues (register of component + pattern matching/id as dict).

**Comment by sdementen** [comment]
Hello @emilhe , I need to refactor the code as handling the pattern matching in callbacks is tricky. I may have something soon.
Tell me if you want to discuss the topic in the meantime.

**Comment by emilhe** [comment]
@sdementen I really like the idea about composed components, but I think some react magic is needed to push the concept across the finish like. Maybe something like a `ComposedComponentBase` (or whatever you would like to call it) that has,

1) A data property of type object to hold state (e.g. similar to a storage)
2) The ability to synchronize properties in the react layer, i.e. without using callbacks

I am aware that (1) can be achieved by adding a storage component in the Dash layer, but i think it might be simpler (and possibly more performant?) to keep the state within the composed component, and it should be straight forward to implement. Obviously, (2) will improve performance as Dash callbacks are avoided. Furthermore, it should solve the issue of composed component registration that you are currently facing. I have a kind-of working prototype for (2), but it utilizes some not-so-nice hacks to keep the children updated (i edit the react key property manually....). I am currently trying to figure out how to do it right :)

**Comment by sdementen** [comment]
I was thinking about components without specific storage should be possible with use of aliases to make internal components properties accessible from the outside.
Syncing the different components within a composed component should still be done on server side (with callbacks), correct?

**Comment by emilhe** [comment]
No, it was my intention to do it client side. I just created a post demonstrating the current syntax,

https://community.plotly.com/t/bidirectional-component-synchronization/47028

but it's still very much work in progress :)

**Comment by sdementen** [comment]
hello @emilhe , I pushed a refactoring of the branch to handle properly the "pattern matching".
I have a couple of exemples in https://github.com/sdementen/dash-extensions/blob/composed-components/examples/ one of which with the synchronisation of two inputs (see https://github.com/sdementen/dash-extensions/blob/composed-components/examples/composed_component_slider.py)

It is all about mangling properly the ids of the components inside a composed component (and adapt the callbacks dependencies accordingly) ... quite a challenge !

**Comment by emilhe** [comment]
This idea seems to have stalled. I will close it for now, please reopen if there is any news.

**Pull request closed without merging**
