### PR TITLE
Fixing the BlockingCallbackTransform for a single list output

### PR DESCRIPTION
**Pull request by TomaszRewak**
The current implementation does not work for the following example:

```python
app.layout = html.Div([
    dcc.Input(id="input", value=""),
    dcc.Dropdown(id="dropdown", options=[]),
])


@app.callback(Output("dropdown", "options"), Input("input", "value"), blocking=True)
def update(value):
    return [value + '_1', value + '_2']
```

That's because the `BlockingCallbackTransform` will see that the `update` function returns a list - and when creating a wrapper around it, it will add the new output value of that wrapper function into that list - instead of adding it as a second return value.

In the example above it results in a value like `["aa_1", "aa_2", end_server_id]`, instead of `[["aa_1", "aa_2"], end_server_id]`.

In this PR I attempt to fix it by making the wrapper generation code context aware, using the expected number of output values when processing the output into a list. If only one output value is expected, even if it's already a list, it is wrapped into a list so that more values can be added next to it.

It also fixes the wrapper generation code for when the single output value is a None (which previously would be converted into `[]` instead of `[None]`).

The presented example is a minimal code that allows for reproducing this behavior, but the most notable example of when a user would encounter this issue is when generating the `data` for a `DataTable` on an interval using the `blocking=True` parameter.

### CODE REVIEW

**Comment by emilhe** [comment]
I tried reproducing the issue with the latest version of dash-extensions. My app looks like this,

```
from enrich import DashProxy, html, dcc, Output, Input

app = DashProxy()
app.layout = html.Div([
    dcc.Input(id="input", value=""),
    dcc.Dropdown(id="dropdown", options=[]),
])


@app.callback(Output("dropdown", "options"), Input("input", "value"), blocking=True)
def update(value):
    return [value + '_1', value + '_2']

app.run_server()
```

and I don't see any errors. Can you check if the error persists in the latest version? And if it does post an updated MWE? :)

**Comment by emilhe** [comment]
I have made an attempt to implement you fix in the current code base. Does is look OK to you? :)

https://github.com/thedirtyfew/dash-extensions/pull/163

**Comment by TomaszRewak** [comment]
Yes, looks good! 🎉

**Comment by emilhe** [comment]
Moved to #163

**Pull request closed without merging**
