### PR TITLE
Fix for no-output enrichment for multi-worker environments, e.g. Gunicorn

### LINKED ISSUE #80: Multi-threading: the no-output enhancement does not work when running Dash with Gunicorn
I'm running the official [callback_no_output.py](https://github.com/thedirtyfew/dash-extensions/blob/master/examples/callback_no_ouput.py) example. 

First thing, installing gunicorn: `pip install gunicorn`

Then, the only thing need to change in the example file is adding this line:

``` python
server = app.server
```

Run with gunicorn:
``` bash
gunicorn examples.callback_no_ouput:server
```

By default, gunicorn runs with one worker, and the example works fine.

----

However, when running with more then one worker, the example doesn't work:

``` bash
gunicorn --workers=2 examples.callback_no_ouput:server
```

The server runs, the page shows the button as expected, but clicking the buttons does nothing.

### Python error:

```
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/fran/.pyenv/versions/3.8.10/envs/dash-extensions/lib/python3.8/site-packages/dash/dash.py", line 1072, in dispatch
    func = self.callback_map[output]["callback"]
KeyError: '0cd4dea8-0137-4c83-b039-33fe63b48634.children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fran/.pyenv/versions/3.8.10/envs/dash-extensions/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/fran/.pyenv/versions/3.8.10/envs/dash-extensions/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/fran/.pyenv/versions/3.8.10/envs/dash-extensions/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/fran/.pyenv/versions/3.8.10/envs/dash-extensions/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/fran/.pyenv/versions/3.8.10/envs/dash-extensions/lib/python3.8/site-packages/dash/dash.py", line 1075, in dispatch
    raise KeyError(msg.format(output))
KeyError: "Callback function not found for output '0cd4dea8-0137-4c83-b039-33fe63b48634.children', perhaps you forgot to prepend the '@'?"

```

### Browser error:

```
dash_renderer.v1_8_3m1604000091.min.js:20 TypeError: Cannot read property 'children' of undefined
    at Li (dash_renderer.v1_8_3m1604000091.min.js:20)
    at dash_renderer.v1_8_3m1604000091.min.js:20
    at new Promise (<anonymous>)
    at qi (dash_renderer.v1_8_3m1604000091.min.js:20)
    at dash_renderer.v1_8_3m1604000091.min.js:20
    at ot (dash_renderer.v1_8_3m1604000091.min.js:20)
    at dash_renderer.v1_8_3m1604000091.min.js:20
    at dash_renderer.v1_8_3m1604000091.min.js:20
    at t (dash_renderer.v1_8_3m1604000091.min.js:20)
    at dash_renderer.v1_8_3m1604000091.min.js:20
```

### PR DESCRIPTION
**Pull request by frnhr**
The issue is that new "dummy" `Div` elements (used for hidden outputs) get their id value generated randomly (`uuid.uuid4()`). This works when a single worker runs the app. However, if multiple workers run the app, each worker will get different UUID value, and the callbacks won't run. See issue #80 

This PR replaces `uuid.uuid4()` call with `uuid.UUID(bytes=seed, version=4)`. The `seed` is a string that will be unique for each callback, and therefore the resulting UUID value will be the same for all workers.

There are three different types of callbacks (Python, JS literal function, JS asset reference), and each needs a separate way of generating the "seed" string.

Closes #80

### CODE REVIEW

**Comment by emilhe** [comment]
Thanks for the PR. I looked through the code, and I really like the idea. However, I had a few ideas on how to simplify the code. I wasn't sure how to suggest them in the best way, so i created a branch with the changes,

https://github.com/thedirtyfew/dash-extensions/tree/no-output-multi-worker

Do you think it looks OK?

**Comment by frnhr** [comment]
Hi @emilhe, it's good to hear back from you!

I really love your simplification. I have merged your branch into this PR, leaving in the changes that I made to the example app, to be able to test it with both variants of clientside callbacks. IMO it makes sense to test and show examples of both variants, but you might also want to keep the example apps as small as possible...

But back to the main topic - The only thing I would change from your simplified code is the condition to detect clientside vs. Python callbacks. I'm worried that `ClientsideFunction` actually has a `__module__` attribute. So it seems a bit "risky" to *only* relay on it not having the `__name__` attribute. Here is the simple change of the condition (also in this PR):
https://github.com/thedirtyfew/dash-extensions/pull/81/commits/3220739729810d818747d103888bab52db9e05b0

**Comment by emilhe** [comment]
I tested my proposed solution, and it seemed to work. I think the modification you proposed it similarly robust though, so let's just keep it as-is.

**Comment by emilhe** [comment]
I have merged the PR and pushed a new release, which should include the fix,

https://pypi.org/project/dash-extensions/0.0.56/

**Pull request merged**
